cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    
]

shoping/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('zarin/searchnew/' ,views.SearchView.as_view(), name="searchnew"),
    path("zarinteb/about-page/", views. MyShopOrder.as_view(), name="about-page"),
    #path ('search/products', views.filter_product, name='searcher'),
    
]

zarin/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

# from .views import Home
# from payment.views import send_request, verify

from django.contrib import admin
admin.site.site_header = 'لوازم پزشکی امیر'
admin.site.site_title = 'لوازم پزشکی زرین طب باستان'

urlpatterns = [
    path('amir/', admin.site.urls),
   
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shoping.urls', namespace='shop')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    #path('zarin/request/', send_request, name='request'),
    #path('zarin/verify/', verify , name='verify'),



]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shoping.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()                                                              
    return render(request, 'cart/detail.html', {'cart': cart,'coupon_apply_form': coupon_apply_form})

cart/templates/cart/default_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Your shopping cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Remove" %}</th>
        <th>{% trans "Unit price" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="{% trans 'حذف محصول' %}">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">تومان{{ item.price }}</td>
            <td class="num">تومان{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">تومان{{ cart.get_total_price|floatformat:0 }}</td>
        </tr>
        <tr>
          {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
            <td>"{{ code }}" coupon ({{ discount }}% off)</td>
          {% endblocktrans %}
          <td colspan="4"></td>
          <td class="num neg">
            - تومان{{ cart.get_discount|floatformat:0 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">
          تومان{{ cart.get_total_price_after_discount|floatformat:0 }}
        </td>
      </tr>
    </tbody>
  </table>

  {% if recommended_products %}
    <div class="recommendations cart">
      <h3>{% trans "People who bought this also bought" %}</h3>
      {% for p in recommended_products %}
        <div class="item">
          <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}
            {% static 'img/no_image.png' %}{% endif %}">
          </a>
          <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <p>{% trans "Apply a coupon" %}:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
  </form>

  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">{% trans "ادامه خرید" %}</a>
    <a href="{% url 'orders:order_create' %}" class="button">
      {% trans "پرداخت نهایی" %}
    </a>
  </p>
{% endblock %}

cart/templates/cart/detail.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fa-IR" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>عنوان سایت | سبد خرید</title>
    <!--search engines description (must be dynamic)-->
    <meta name="description" content="توضیحات محصول">
    <link rel="stylesheet" href="{% static 'css/styles/main.css' %}">
     <link rel="stylesheet" href="{% static 'css/styles/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/font-awesome.min.css' %}">
   
    <script src="https://kit.fontawesome.com/a27e5077f7.js" crossorigin="anonymous"></script>
</head>
<body>
    <!--start Header-->
  
    <header id="header">
        <div id="contact_info">
            <div id="left">
                <!--support number-->
                <a href="tel: 09131696378">
                    <span id="number"><i class="fa fa-phone" aria-hidden="true"></i> 09131696378 تماس با پشتیبانی</span>
                </a>
            </div>
            <div id="center">
                <!--site title-->
            <h1>زرین طب <span>باستان </span> <img src="{% static 'images/logo.png' %}" width="68px" alt=""></h1>
               
            </div>
            <div id="right">
                <ul>
                    <!--social networks-->
                    <a href="#instagram"><li class="fa fa-instagram" aria-hidden="true"></li></a>
                    <a href="#telegram"><li class="fa fa-telegram" aria-hidden="true"></li></a>
                    <a href="#facebook"><li class="fa fa-facebook-square" aria-hidden="true"></li></a>
                    <a href="#twitter"><li class="fa fa-twitter" aria-hidden="true"></li></a>
                    <a href="#email"><li class="fa fa-envelope" aria-hidden="true"></li></a>
                </ul>
            </div>
        </div>
        <div class="clr"></div>
        <div id="second_row">
            <!--search box start-->
            <div id="search_box">
                <form class="searchForm-head" id="searchform" action="{% url 'shop:searchnew' %}" method="get">
                    <div id="input">
                    <input type="text" name="q" data-toggle="popover" data-placement="bottom" data-content="Press enter to search" class="search__field" placeholder="چیزی وارد کنید ..." value="" style="" data-original-title="" title="" autofocus="autofocus">   
                      <!-- <button type="button" onclick="searchform.submit()" class="btnSeaech search__btn"></button> -->
                      <input type="submit" onclick="searchform.submit()" value="">
                    </div>
                    </form>
            </div>
            <!--/search box end-->
            <div id="details">
                <ul> 
                    <li id="basket">
                        <!--basket-->
                        <div class="fa fa-shopping-cart icon"></div>
                        <div class="title">سبد خرید
                            <span id="count">
                            {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                                <a href="{% url 'cart:cart_detail' %}">
                                {{ total_items }}
                                </a>
                            {% else %}
                            سبد شما خالی
                            {% endif %}
                            {% endwith %}
                            </span>
                        </div>
                    </li>
                    <li id="user_area">
                        <!--login/signup area-->
                        <div class="fa fa-user icon"></div>
                        <div class="title"><a class="js-open-modal btn" href="">ورود / ثبت نام</a></div>
                    </li>
                </ul>
            </div>
            <!--the login/signup popup-->
            <div id="popup1" class="modal-box">
                <header> <a href="" class="js-modal-close close">×</a>
                  <h3>ورود یا عضویت</h3>
                </header>
                <div class="modal-body">
                    <!--form must be here-->

                </div>
              </div>
        </div>
        <div class="clr"></div>
        <nav id="top_navi">
            <div id="mnu-btn" class="fa fa-bars"></div>
            <ul>
                <!--navigation menu-->
                <li><a href="{% url 'shop:product_list' %}">صفحه ی نخست</a></li>
                <li><a href="#">درباره ی ما</a></li>
                <li><a href="#">تماس با ما</a></li>
                <li class="have-child"><a href="#">دسته بندی محصولات</a>
                <!--the menu can unlimited child-->
                <!--start child-->
                <ul>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %} {% endif %}>
                    
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                        
                  
                    {% endfor %}
                </ul>
              
                  </li>
                <!--/end child-->
                </li>
            </ul>
        </nav>
        <div class="clr"></div>
 
    <!--/end Header-->
    <div class="clr"></div>
    <div id="contain">
        <section id="basket">
            <table>
                <thead>
                    <tr>
                        <td>تصویر</td>
                        <td>عنوان</td>
                        <td>تعداد</td>
                        <td>حذف</td>
                        <td>قیمت واحد</td>
                        <td>قیمت</td>
                    </tr>
                </thead>
                <tbody>
                    <!--start loop-->
                    {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td class="image"><a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image1 %}{{ product.image1.url }}
                            {% else %}{% static 'img/no_image.png' %}{% endif %}">
                          </a></td>
                        <td>
                            <h4>{{ product.name }}</h4>
                        </td>
                        <td><form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" value="بروزرسانی سبد">
                            {% csrf_token %}
                          </form></td>
                        <td>
                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                <input type="submit" value="{% trans 'حذف محصول' %}">
                                {% csrf_token %}
                              </form>
                        </td>
                        <td class="num">تومان{{ item.price }}</td>
                             <td class="num">تومان{{ item.total_price }}</td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                    
                    {% if cart.coupon %}
                    <tr class="subtotal">
                      <td>{% trans "جمع کل با تخفیف" %}</td>
                      <td colspan="4"></td>
                      <td class="num">تومان{{ cart.get_total_price|floatformat:0 }}</td>
                    </tr>
                    <tr>
          {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
            <td>"{{ code }}" coupon ({{ discount }}% off)</td>
          {% endblocktrans %}
          <td colspan="4"></td>
          <td class="num neg">
            - تومان{{ cart.get_discount|floatformat:0 }}
          </td>
        </tr>
      {% endif %}
                    
                    
                  
                    <!--/end loop-->
                </tbody>
            </table>
            <div id="go-pay"> <a href="{% url 'orders:order_create' %}" class="button">
                {% trans "ادامه جهت تسویه حساب" %}
              </a></div>
            <div class="clr"></div>
        </section>
    </div>
        <!--footer-->
        <footer id="footer">
            <div id="boxes">
                <!--first-->
                <div class="box">
                    <h3>دسترسی سریع</h3>
                    <div class="content">
                        <ul>
                            <li><a href="#">تجهیزات پزشکی</a></li>
                        </ul>
                    </div>
                </div>
                <!--second-->
                <div class="box">
                    <h3>تاییدیه و مجوزها</h3>
                    <div class="content">
                        <img src="images/nam.png" alt="">
                    </div>
                </div>
                <!--third-->
                <div class="box">
                    <h3>تماس با ما</h3>
                    <div class="content">
                        <p>آدرس : اصفهان - خیابان شیخ بهایی</p>
                    </div>
                </div>
            </div>
            <div class="clr"></div>
            <!--copyright-->
            <p id="copyright">کلیه ی حقوق این وبسایت محفوظ می باشد و هرگونه کپی برداری از آن شرعا و قانونا غیرمجاز است.</p>
        </footer>
        <!--whatsapp widget-->
        <div id="whatsapp_support" class="fa fa-whatsapp">
                 <a href="https://web.whatsapp.com/send?phone=09131696378&text=سلام"><div id="title">پشتیبانی واتساپ</div>
            </a>
        </div>
    <!--load Scripts-->
    <script src="{% static 'js/scripts/jquery-3.5.1.min.js' %}"></script>
  
    <script src="{% static 'js/scripts/scripts.js' %}"></script>
</body>

</html>