cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    
]

shoping/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('zarin/searchnew/' ,views.SearchView.as_view(), name="searchnew"),
    path("zarinteb/about-page/", views. MyShopOrder.as_view(), name="about-page"),
    #path ('search/products', views.filter_product, name='searcher'),
    
]

zarin/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

# from .views import Home
# from payment.views import send_request, verify

from django.contrib import admin
admin.site.site_header = 'لوازم پزشکی امیر'
admin.site.site_title = 'لوازم پزشکی زرین طب باستان'

urlpatterns = [
    path('amir/', admin.site.urls),
   
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shoping.urls', namespace='shop')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    #path('zarin/request/', send_request, name='request'),
    #path('zarin/verify/', verify , name='verify'),



]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator, \
                                   MaxValueValidator
from django.utils.translation import gettext_lazy as _
from shoping.models import Product
from coupons.models import Coupon
from django_jalali.db import models as jmodels

from django.contrib.auth.models import User


class Order(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)   
    address = models.CharField(max_length=250, verbose_name="آدرس")
    postal_code = models.CharField(max_length=20, verbose_name="کدپستی")
    city = models.CharField(max_length=100, verbose_name="شهر | استان")
    created = jmodels.jDateField(auto_now_add=True , verbose_name="تاریخ ایجاد")
    updated = jmodels.jDateField(auto_now=True, verbose_name="تاریخ تغییر")
    paid = models.BooleanField(default=False, verbose_name="وضعیت پرداخت")
    coupon = models.ForeignKey(Coupon,
                               related_name='orders',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL, verbose_name="تخفیف")
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])

    
    
    
    
    class Meta:
        ordering = ('-created',)


    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * \
            (self.discount / Decimal(100))


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    quantity = models.PositiveIntegerField(default=1, verbose_name="تعداد")

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

shoping/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
from django_jalali.db import models as jmodels


class PostManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(name__icontains=query) |
                         Q(name__icontains=query)

                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs

class PriceManager(models.Manager):# اسلایدر اولی سمت چپ
     def get_queryset(self):
       # return super(PriceManager, self).get_queryset().filter(pk__in=[2])
         return super(PriceManager, self).get_queryset().filter(new_category=True).filter(subcategory__id=1)


class AdvansedManager(models.Manager):
     def get_queryset(self):
      
         return super(AdvansedManager, self).get_queryset().filter(new_category=False).filter(subcategory__id=3)



class AdvansedManagerTak(models.Manager):# اولین تصویر سمت راست
     def get_queryset(self):
      
         return super(AdvansedManagerTak, self).get_queryset().filter(new_category=False).filter(subcategory__id=4) # تک جنس







class Category(models.Model):
    name = models.CharField(max_length=200,  db_index=True ,verbose_name="نام- دسته بندی")
    slug = models.SlugField(max_length=200,unique=True)
    parent=models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    objects           = PostManager() 
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'دسته بندی محصولات'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])




class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='souscatégories', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True , verbose_name="نام")
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = jmodels.jDateField(auto_now_add=True , verbose_name="تاریخ ایجاد")
    updated_at = jmodels.jDateField(auto_now=True, verbose_name="تاریخ تغییر")
    
    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'زیر منو'
        verbose_name_plural = 'زیر منوها'
    
    def __str__(self):
        
         return self.name






class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True, verbose_name="نام کالا")
    slug = models.SlugField(max_length=200, db_index=True)
    image1 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True , verbose_name="تصویر اول")
    image2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True , verbose_name="تصویر دوم")
    description = models.TextField(blank=True, verbose_name='شرح کالا')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="قیمت کالا")
    available = models.BooleanField(default=True, verbose_name="موجودی")
    color = models.CharField(max_length=10, null=True, verbose_name="رنگ کالا")
    country =  models.CharField(max_length=30, verbose_name="کشور سازنده")
    created = jmodels.jDateField(auto_now_add=True , verbose_name="تاریخ ایجاد")
    updated = jmodels.jDateField(auto_now=True, verbose_name="تاریخ تغییر")
    new_category = models.BooleanField(default=True, verbose_name="ویژه")
    subcategory = models.ForeignKey(SubCategory, related_name='produits', on_delete=models.CASCADE)
    


    objects = models.Manager() # The default manager.
    objects           = PostManager() 
    lavazemA=  PriceManager()
    advansed_product = AdvansedManager()
    tak_es = AdvansedManagerTak()

    class Meta:
        
        ordering = ('created',)
        index_together = (('id', 'slug'),)
        verbose_name_plural = 'محصول'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address',
                  'postal_code', 'city']

orders/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from cart.cart import Cart
from .models import OrderItem, Order
from .forms import OrderCreateForm
from .tasks import order_created

#
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from .models import Order



#
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
#import weasyprint



"""
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # launch asynchronous task
            
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})

"""





def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # launch asynchronous task
            #order_created.delay(order.id)
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})





@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})




@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
        stylesheets=[weasyprint.CSS(
            settings.STATIC_ROOT + 'css/pdf.css')])
    return response

shoping/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product, SubCategory
from itertools import chain
from django.http import HttpResponse


from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
from django.views.generic import ListView, DetailView, CreateView, DeleteView

from django.views.generic import TemplateView

#from.filters import ProductFilter

def product_list(request, category_slug=None, sub_slug=None):
    category = None
    categories = Category.objects.all()
    subs = SubCategory.objects.all()
    products = Product.objects.filter(available=True)
    new_product= Product.lavazemA.all()
    advansed_pro =Product.advansed_product.all()
    taki= Product.tak_es.all()
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    if sub_slug:
        subs = get_objects_or_404(SubCategory, slug=sub_slug)
        products = products.filter(subcategory=subs)
       
       
       
    return render(request,
                  'shop/product/just.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,'subs':subs,'new_product':new_product, 'advansed':advansed_pro,'taki':taki})





def product_detail(request, id, slug):
   
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product/page-single.html',
                  {'product': product,"cart_product_form":cart_product_form})



class SearchView(ListView):
    template_name = "view.html"
    paginate_by = 20
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)

        if query is not None:
            blog_results = Product.objects.search(query)
            #lesson_results = Product.objects.search(query)
            #profile_results = Service.objects.search(query)

            # combine querysets 
            queryset_chain = chain(
                blog_results,
                #lesson_results,
                #profile_results
            )
            qs = sorted(queryset_chain,
                        key=lambda instance: instance.pk,
                        reverse=True)
            self.count = len(qs)  # since qs is actually a list
            return qs
        return Product.objects.none()  # just an empty queryset as default
        

# filter product 

# def filter_product(request):
#      f = ProductFilter(request.GET, queryset=Product.objects.all())
#      return render(request, "shop/product/filter_1.html", {"filter":f})

       
       
       
        
        
class MyShopOrder(TemplateView):
    template_name ="shop/product/order.html"
        
        
        
        

shoping/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">تومان{{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="خرید">
    </form>
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

shoping/templates/shop/product/filter_1.html
  <form method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.name }} - تومان{{ obj.price }}<br />
    {% endfor %}

shoping/templates/shop/product/header.html
{% load static %}
<!DOCTYPE html>
<html lang="fa-IR" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>لوازم پزشکی  اصفهان | زرین طب باستان | پزشکی اصفهان</title>
    <!--search engines description (must be dynamic)-->
    <meta name="description" content="توضیحات فروشگاه اینترنتی">
    <link rel="stylesheet" href="{% static 'css/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/flickity.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/font-awesome.min.css' %}">
    
    <script src="https://kit.fontawesome.com/a27e5077f7.js" crossorigin="anonymous"></script>
</head>
<body>
    <!--start Header-->
    <header id="header">
        <div id="contact_info">
            <div id="left">
                <!--support number-->
                <a href="tel: 09131696378">
                    <span id="number"><i class="fa fa-phone" aria-hidden="true"></i> 09131696378 تماس با پشتیبانی</span>
                </a>
            </div>
            <div id="center">
                <!--site title-->
            <h1>زرین طب <span>باستان </span> <img src="{% static 'images/logo.png' %}" width="68px" alt=""></h1>
               
            </div>
            <div id="right">
                <ul>
                    <!--social networks-->
                    <a href="#instagram"><li class="fa fa-instagram" aria-hidden="true"></li></a>
                    <a href="#telegram"><li class="fa fa-telegram" aria-hidden="true"></li></a>
                    <a href="#facebook"><li class="fa fa-facebook-square" aria-hidden="true"></li></a>
                    <a href="#twitter"><li class="fa fa-twitter" aria-hidden="true"></li></a>
                    <a href="#email"><li class="fa fa-envelope" aria-hidden="true"></li></a>
                </ul>
            </div>
        </div>
        <div class="clr"></div>
        <div id="second_row">
            <!--search box start-->
            <div id="search_box">
                <form class="searchForm-head" id="searchform" action="{% url 'shop:searchnew' %}" method="get">
                    <div id="input">
                    <input type="text" name="q" data-toggle="popover" data-placement="bottom" data-content="Press enter to search" class="search__field" placeholder="چیزی وارد کنید ..." value="" style="" data-original-title="" title="" autofocus="autofocus">   
                      <!-- <button type="button" onclick="searchform.submit()" class="btnSeaech search__btn"></button> -->
                      <input type="submit" onclick="searchform.submit()" value="">
                    </div>
                    </form>
            </div>
            <!--/search box end-->
            <div id="details">
                <ul> 
                    <li id="basket">
                        <!--basket-->
                        <div class="fa fa-shopping-cart icon"></div>
                        <div class="title">سبد خرید
                            {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                            <span id="count">
                            <a href="{% url 'cart:cart_detail' %}">{{ total_items }}</a>
                            </span>
                            {% endif %}
                            {% endwith %}
                        </div>
                    </li>
                    <li id="user_area">
                        <!--login/signup area-->
                        <div class="fa fa-user icon"></div>
                        <div class="title"><a class="js-open-modal btn" href="">ورود / ثبت نام</a></div>
                    </li>
                </ul>
            </div>
            <!--the login/signup popup-->
            <div id="popup1" class="modal-box">
                <header> <a href="" class="js-modal-close close">×</a>
                  <h3>ورود یا عضویت</h3>
                </header>
                <div class="modal-body">
                    <!--form must be here-->

                </div>
              </div>
              
        </div>
        <div class="clr"></div>
        <nav id="top_navi">
            <div id="mnu-btn" class="fa fa-bars"></div>
            <ul>
                <!--navigation menu-->
                 <li ><a href="">سرچ قوی</a>
                <li><a href="{% url 'shop:product_list' %}">صفحه ی نخست</a></li>
                <li><a href="{% url 'shop:about-page' %}">درباره ی ما</a></li>
                <li><a href="#">تماس با ما</a></li>
                <li class="have-child"><a href="#">دسته بندی محصولات</a>
                
                
                <!--the menu can unlimited child-->
                <!--start child-->
                <ul>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %} {% endif %}>
                    
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                        
                  
                    {% endfor %}
                </ul>
              
                  </li>
                  
                   
                  
                  
                <!--/end child-->
                </li>
                <li class="have-child"><a href="{% url 'shop:product_list' %}">همه محصولات</a></li>
            </ul>
        </nav>
        <div class="clr"></div>
    </header>
    <!--/end Header-->
    <div class="clr"></div>

shoping/templates/shop/product/order.html
{% load static %}
<!DOCTYPE html>
<html lang="fa-IR" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>نام دسته بندی ، نتیجه ی جستجو یا تگ یا آرشیو</title>
    <!--search engines description (must be dynamic)-->
    <meta name="description" content="توضیحات محصول">
    <link rel="stylesheet" href="{% static 'css/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/flickity.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles/font-awesome.min.css' %}">
    <script src="https://kit.fontawesome.com/a27e5077f7.js" crossorigin="anonymous"></script>
</head>
<body>
    <!--start Header-->
   <header id="header">
        <div id="contact_info">
            <div id="left">
                <!--support number-->
                <a href="tel: 09131696378">
                    <span id="number"><i class="fa fa-phone" aria-hidden="true"></i> 09131696378 تماس با پشتیبانی</span>
                </a>
            </div>
            <div id="center">
                <!--site title-->
            <h1>زرین طب <span>باستان </span> <img src="{% static 'images/logo.png' %}" width="68px" alt=""></h1>
               
            </div>
            <div id="right">
                <ul>
                    <!--social networks-->
                    <a href="#instagram"><li class="fa fa-instagram" aria-hidden="true"></li></a>
                    <a href="#telegram"><li class="fa fa-telegram" aria-hidden="true"></li></a>
                    <a href="#facebook"><li class="fa fa-facebook-square" aria-hidden="true"></li></a>
                    <a href="#twitter"><li class="fa fa-twitter" aria-hidden="true"></li></a>
                    <a href="#email"><li class="fa fa-envelope" aria-hidden="true"></li></a>
                </ul>
            </div>
        </div>
        <div class="clr"></div>
        <div id="second_row">
            <!--search box start-->
            <div id="search_box">
                <form class="searchForm-head" id="searchform" action="" method="get">
                    <div id="input">
                    <input type="text" name="q" data-toggle="popover" data-placement="bottom" data-content="Press enter to search" class="search__field" placeholder="چیزی وارد کنید ..." value="" style="" data-original-title="" title="" autofocus="autofocus">   
                      <!-- <button type="button" onclick="searchform.submit()" class="btnSeaech search__btn"></button> -->
                      <input type="submit" onclick="searchform.submit()" value="">
                    </div>
                    </form>
            </div>
            <!--/search box end-->
            <div id="details">
                <ul> 
                    <li id="basket">
                        <!--basket-->
                        <div class="fa fa-shopping-cart icon"></div>
                        <div class="title">سبد خرید
                            <span id="count">
                            {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                                <a href="{% url 'cart:cart_detail' %}">
                                {{ total_items }}
                                </a>
                            {% else %}
                            سبد شما خالی
                            {% endif %}
                            {% endwith %}
                            </span>
                        </div>
                    </li>
                    <li id="user_area">
                        <!--login/signup area-->
                        <div class="fa fa-user icon"></div>
                        <div class="title"><a class="js-open-modal btn" href="">ورود / ثبت نام</a></div>
                    </li>
                </ul>
            </div>
            <!--the login/signup popup-->
            <div id="popup1" class="modal-box">
                <header> <a href="" class="js-modal-close close">×</a>
                  <h3>ورود یا عضویت</h3>
                </header>
                <div class="modal-body">
                    <!--form must be here-->

                </div>
              </div>
        </div>
        <div class="clr"></div>
        <nav id="top_navi">
            <div id="mnu-btn" class="fa fa-bars"></div>
            <ul>
                <!--navigation menu-->
                <li><a href="{% url 'shop:product_list' %}">صفحه ی نخست</a></li>
                <li><a href="#">درباره ی ما</a></li>
                <li><a href="#">تماس با ما</a></li>
                <li class="have-child"><a href="#">دسته بندی محصولات</a>
                <!--the menu can unlimited child-->
                <!--start child-->
                <ul>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %} {% endif %}>
                    
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                        
                  
                    {% endfor %}
                </ul>
              
                  </li>
                <!--/end child-->
                </li>
            </ul>
        </nav>
        <div class="clr"></div>
    </header>

    <!--/end Header-->
    <div class="clr"></div>
    <div id="contain">
        <!--start grids-->
        <section id="grids">
            <h2>درباره ما - تجهیزات پزشکی زرین طب باستان | تهیه و توزیع کلیه تجهیزات پزشکی و درمانی و بهداشتی ...</h2>
            <hr>
            <br>
           <p>گروه زرین طب باستان در سال 1398 تاسیس شد و تا کنون بر ارائه خدمات  مطمئن و تخصصی جهت  فروش کالاهای پزشکی و درمانی تمرکز و فعالیت نموده است. ما مفتخریم که در راستای خدمات مطلوب به مشتریان عزیز در سراسر کشور سهیم باشیم. 
.</p>
            
        </section>
        <!--/end grids-->
        <!--start pagination-->
      
        <div class="clr"></div>
        <!--/end pagination-->
    </div>
        <!--footer-->
        <footer id="footer">
            <div id="boxes">
                <!--first-->
                <div class="box">
                    <h3>دسترسی سریع</h3>
                    <div class="content">
                        <ul>
                            <li><a href="#">تجهیزات پزشکی</a></li>
                        </ul>
                    </div>
                </div>
                <!--second-->
                <div class="box">
                    <h3>تاییدیه و مجوزها</h3>
                    <div class="content">
                        <img src="images/nam.png" alt="">
                    </div>
                </div>
                <!--third-->
                <div class="box">
                    <h3>تماس با ما</h3>
                    <div class="content">
                        <p>آدرس : اصفهان - خیابان شیخ بهایی</p>
                    </div>
                </div>
            </div>
            <div class="clr"></div>
            <!--copyright-->
            <p id="copyright">کلیه ی حقوق این وبسایت محفوظ می باشد و هرگونه کپی برداری از آن شرعا و قانونا غیرمجاز است.</p>
        </footer>
        <!--whatsapp widget-->
        <div id="whatsapp_support" class="fa fa-whatsapp">
            <a href="https://web.whatsapp.com/send?phone=989123456789&text=سلام"><div id="title">پشتیبانی واتساپ</div>
            </a>
        </div>
    <!--load Scripts-->

  
    <script src="{% static 'js/scripts/jquery-3.5.1.min.js' %}"></script>
  
    <script src="{% static 'js/scripts/scripts.js' %}"></script>
    <div id="overlay"></div>
</body>

</html>